name: Release tagged build
description: 'Release tagged build on another repo (RetroFuturaGradle)'
inputs:
  gh_repo:
    description: 'Github repo to operate on'
    required: true
  GITHUB_TOKEN:
    description: 'set to the value of a secret containing a token with read/write permissions for the repo'
    required: true
  use_absver:
    description: 'set this to any value except false to use absolute versioning in filenames/release info'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    ENABLEABSVER: $[{ inputs.use_absver }]
    GHREPO: $[{ inputs.gh_repo }]
