name: Sync SeamlessAuth mirror
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: lubinacourec/gh-mirror-action@master
        with:
          origin: 'https://codeberg.org/Anonymouse/Seamless-Auth.git'
          mirror: 'lubinacourec/SeamlessAuth'
          GITHUB_TOKEN: ${{ secrets.SEAMLESSAUTH_GITHUB_TOKEN }}
